all: hw5_q1 hw5_q2 hw5_q3 hw5_q4 hw5_q5

hw5_q1: hw5_q1.c
	gcc -o hw5_q1 hw5_q1.c

hw5_q2: hw5_q2.c
	gcc -o hw5_q2 hw5_q2.c

hw5_q3: hw5_q3.c
	gcc -o hw5_q3 hw5_q3.c

hw5_q4: hw5_q4.c
	gcc -o hw5_q4 hw5_q4.c

hw5_q5: hw5_q5.c
	gcc -o hw5_q5 hw5_q5.c

clean:
	rm -f hw5_q1 hw5_q2 hw5_q3 hw5_q4 hw5_q5
